// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.controller;

import org.junit.jupiter.api.Test;
import org.springframework.mock.web.MockHttpServletResponse;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class PostController_redirect_31b271143a_Test {

    @Test
    public void testRedirectSuccess() throws IOException {
        PostController postController = new PostController();
        MockHttpServletResponse response = new MockHttpServletResponse();
        
        postController.redirect(response);
        
        assertEquals("/swagger-ui.html", response.getRedirectedUrl());
    }

    @Test
    public void testRedirectFailure() throws IOException {
        PostController postController = new PostController();
        MockHttpServletResponse response = new MockHttpServletResponse();
        
        response.sendError(HttpServletResponse.SC_NOT_FOUND);
        postController.redirect(response);
        
        assertEquals(HttpServletResponse.SC_NOT_FOUND, response.getStatus());
    }
}
