// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class Post_getProfile_ce58a7beef_Test {

    @Test
    public void testGetProfileSuccess() {
        Post post = new Post();
        post.setProfile("Software Engineer");
        String profile = post.getProfile();
        assertEquals("Software Engineer", profile, "Profile should be Software Engineer");
    }

    @Test
    public void testGetProfileFailure() {
        Post post = new Post();
        post.setProfile("Data Analyst");
        String profile = post.getProfile();
        assertEquals("Software Engineer", profile, "Profile should be Software Engineer but was " + profile);
    }
}
