// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertArrayEquals;

public class Post_setTechs_1b061b0fa7_Test {

    @Mock
    private Post post;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetTechs_Success() {
        String[] expectedTechs = {"Java", "Spring Boot"};
        post.setTechs(expectedTechs);
        assertArrayEquals(expectedTechs, post.getTechs());
    }

    @Test
    public void testSetTechs_EmptyArray() {
        String[] expectedTechs = {};
        post.setTechs(expectedTechs);
        assertArrayEquals(expectedTechs, post.getTechs());
    }
}
