// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class Post_getExp_e90c52dc7e_Test {

    private Post post;

    @BeforeEach
    public void setUp() {
        post = new Post();
    }

    @Test
    public void testGetExp_PositiveExp() {
        // TODO: Set the exp value to a positive number
        post.setExp(5);
        int exp = post.getExp();
        Assertions.assertEquals(5, exp, "Expected experience doesn't match actual experience");
    }

    @Test
    public void testGetExp_ZeroExp() {
        // TODO: Set the exp value to zero
        post.setExp(0);
        int exp = post.getExp();
        Assertions.assertEquals(0, exp, "Expected experience doesn't match actual experience");
    }

    @Test
    public void testGetExp_NegativeExp() {
        // TODO: Set the exp value to a negative number
        post.setExp(-3);
        int exp = post.getExp();
        Assertions.assertEquals(-3, exp, "Expected experience doesn't match actual experience");
    }
}
