// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class Post_getDesc_66e632b9da_Test {

    private Post post;

    @BeforeEach
    public void setUp() {
        post = new Post();
    }

    @Test
    public void testGetDesc_WhenDescIsNotNull() {
        // TODO: Replace 'testDesc' with the actual description
        String expectedDesc = "testDesc";
        post.setDesc(expectedDesc);

        String actualDesc = post.getDesc();

        Assertions.assertEquals(expectedDesc, actualDesc, "The expected description does not match with the actual description");
    }

    @Test
    public void testGetDesc_WhenDescIsNull() {
        post.setDesc(null);

        String actualDesc = post.getDesc();

        Assertions.assertNull(actualDesc, "The actual description is not null");
    }
}
