// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class Post_getExp_e90c52dc7e_Test {

    private Post post;

    @BeforeEach
    public void setUp() {
        post = new Post();
    }

    @Test
    public void testGetExp_Success() {
        post.setExp(5);
        int expected = 5;
        int actual = post.getExp();
        assertEquals(expected, actual, "Expected experience does not match actual");
    }

    @Test
    public void testGetExp_Failure() {
        post.setExp(3);
        int expected = 5;
        int actual = post.getExp();
        assertEquals(expected, actual, "Expected experience does not match actual");
    }
}
