// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import org.mockito.Mockito;

public class Post_setDesc_148780b2fa_Test {
    private Post post;

    @BeforeEach
    public void setup() {
        post = Mockito.mock(Post.class);
    }

    @Test
    public void testSetDesc_Success() {
        String expectedDesc = "This is a test description";
        Mockito.doAnswer(invocation -> {
            Object arg0 = invocation.getArgument(0);
            Assertions.assertEquals(expectedDesc, arg0);
            return null;
        }).when(post).setDesc(Mockito.anyString());

        post.setDesc(expectedDesc);
    }

    @Test
    public void testSetDesc_Null() {
        String expectedDesc = null;
        Mockito.doAnswer(invocation -> {
            Object arg0 = invocation.getArgument(0);
            Assertions.assertEquals(expectedDesc, arg0);
            return null;
        }).when(post).setDesc(Mockito.anyString());

        post.setDesc(expectedDesc);
    }
}
