// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.mockito.junit.MockitoJUnitRunner;
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class Post_getDesc_66e632b9da_Test {

    @Mock
    private Post post;

    @Before
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetDescSuccess() {
        String expectedDescription = "This is a test description";
        when(post.getDesc()).thenReturn(expectedDescription);

        String actualDescription = post.getDesc();
        assertEquals(expectedDescription, actualDescription);
    }

    @Test
    public void testGetDescFailure() {
        String unexpectedDescription = "This is a wrong description";
        when(post.getDesc()).thenReturn("This is a test description");

        String actualDescription = post.getDesc();
        assertEquals(false, unexpectedDescription.equals(actualDescription));
    }
}
