// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.data.mongodb.core.mapping.Document;

public class Post_toString_ceffa8036e_Test {

    private Post post;

    @BeforeEach
    public void setUp() {
        post = new Post();
    }

    @Test
    public void testToString() {
        post.setProfile("Software Developer");
        post.setDesc("Java Developer");
        post.setExp(5);
        post.setTechs(new String[]{"Java", "Spring Boot"});
        String expected = "Post{profile='Software Developer', desc='Java Developer', exp=5, techs=[Java, Spring Boot]}";
        Assertions.assertEquals(expected, post.toString());
    }

    @Test
    public void testToString_NoData() {
        String expected = "Post{profile='null', desc='null', exp=0, techs=null}";
        Assertions.assertEquals(expected, post.toString());
    }
}
