// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.boot.test.context.SpringBootTest;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

@SpringBootTest
public class Post_setDesc_148780b2fa_Test {

    @InjectMocks
    private Post post;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testSetDesc_ValidInput() {
        String validDesc = "Valid description";
        post.setDesc(validDesc);
        assertEquals(validDesc, post.getDesc());
    }

    @Test
    public void testSetDesc_NullInput() {
        String nullDesc = null;
        assertThrows(NullPointerException.class, () -> post.setDesc(nullDesc));
    }
}
