// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.springframework.data.mongodb.core.mapping.Document;

public class Post_Post_ec8a5320eb_Test {

    @Test
    public void testPostConstructor() {
        Post post = new Post();
        assertNotNull(post, "Post object should not be null");
    }

    @Test
    public void testPostConstructorWithParameters() {
        Post post = new Post("123", "Java Developer", "Java, Spring Boot", "Telusko", "Mumbai");
        assertEquals("123", post.getId());
        assertEquals("Java Developer", post.getJobTitle());
        assertEquals("Java, Spring Boot", post.getJobDescription());
        assertEquals("Telusko", post.getCompany());
        assertEquals("Mumbai", post.getLocation());
    }

}
