// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Post_getExp_e90c52dc7e_Test {

    @Test
    public void testGetExp() {
        Job job = new Job();
        job.setExp(5);
        assertEquals(5, job.getExp());
    }

    @Test
    public void testGetExpWithZero() {
        Job job = new Job();
        job.setExp(0);
        assertEquals(0, job.getExp());
    }
} 
