// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
public class Post_Post_ec8a5320eb_Test {

    @Test
    public void testPostObjectCreation() {
        Post post = new Post();
        assertNotNull(post, "Post object creation failed!");
    }

    @Test
    public void testPostObjectFields() {
        Post post = new Post();
        assertNull(post.getTitle(), "Newly created post should not have a title");
        assertNull(post.getDescription(), "Newly created post should not have a description");
        assertNull(post.getAuthor(), "Newly created post should not have an author");
    }
}
