// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@SpringBootTest
public class Post_getTechs_443a51e600_Test {

    private String[] techs;
    private Post post;

    @BeforeEach
    public void setUp() {
        techs = new String[]{"Java", "Spring Boot", "MongoDB"};
        post = mock(Post.class);
        when(post.getTechs()).thenReturn(techs);
    }

    @Test
    public void testGetTechs_Success() {
        String[] expectedTechs = {"Java", "Spring Boot", "MongoDB"};
        String[] actualTechs = post.getTechs();
        assertArrayEquals(expectedTechs, actualTechs);
    }

    @Test
    public void testGetTechs_Failure() {
        String[] unexpectedTechs = {"Node.js", "Express.js", "MongoDB"};
        String[] actualTechs = post.getTechs();
        assertNotEquals(Arrays.toString(unexpectedTechs), Arrays.toString(actualTechs));
    }
}
