// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class Post_setTechs_1b061b0fa7_Test {

    @Test
    public void testSetTechs_ValidInput() {
        // Create a new post object
        Post post = new Post();

        // TODO: Replace with valid techs
        String[] techs = {"Java", "Spring Boot", "MongoDB"};

        // Set techs
        post.setTechs(techs);

        // Check if the techs are set correctly
        assertArrayEquals(techs, post.getTechs(), "Techs should be set correctly");
    }

    @Test
    public void testSetTechs_NullInput() {
        // Create a new post object
        Post post = new Post();

        // Set techs to null
        post.setTechs(null);

        // Check if the techs are set to null
        assertNull(post.getTechs(), "Techs should be set to null");
    }
}
