// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Post_getProfile_ce58a7beef_Test {

    @Test
    public void testGetProfileSuccess() {
        Post post = new Post();
        post.setProfile("Developer");
        assertEquals("Developer", post.getProfile());
    }

    @Test
    public void testGetProfileFailure() {
        Post post = new Post();
        post.setProfile("Developer");
        assertNotEquals("Analyst", post.getProfile());
    }
}
