// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.springframework.data.mongodb.core.mapping.Document;
import java.util.Arrays;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Post_getTechs_443a51e600_Test {
    
    @Test
    public void testGetTechs() {
        String[] techs = {"Java", "Python", "C++"};
        Post post = new Post();
        post.setTechs(techs);
        assertArrayEquals(techs, post.getTechs());
    }

    @Test
    public void testGetTechs_Empty() {
        String[] techs = {};
        Post post = new Post();
        post.setTechs(techs);
        assertArrayEquals(techs, post.getTechs());
    }

    @Test
    public void testGetTechs_Null() {
        String[] techs = null;
        Post post = new Post();
        post.setTechs(techs);
        assertNull(post.getTechs());
    }
}
