// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
public class Post_getTechs_443a51e600_Test {

    @Test
    public void testGetTechs() {
        Post post = new Post();
        String[] techs = {"Java", "Spring Boot", "MongoDB"};
        post.setTechs(techs);

        assertArrayEquals(techs, post.getTechs());
    }

    @Test
    public void testGetTechsEmpty() {
        Post post = new Post();
        String[] techs = {};
        post.setTechs(techs);

        assertArrayEquals(techs, post.getTechs());
    }

    @Test
    public void testGetTechsNull() {
        Post post = new Post();
        post.setTechs(null);

        assertNull(post.getTechs());
    }
}
