// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Post_getProfile_ce58a7beef_Test {

    @Test
    public void testGetProfileSuccess() {
        // TODO: Replace 'expectedProfile' with the expected profile string
        String expectedProfile = "Software Engineer";

        Post post = new Post();
        post.setProfile(expectedProfile);

        String actualProfile = post.getProfile();

        assertEquals(expectedProfile, actualProfile);
    }

    @Test
    public void testGetProfileWhenProfileIsNull() {
        Post post = new Post();
        post.setProfile(null);

        String actualProfile = post.getProfile();

        assertEquals(null, actualProfile);
    }
}
