// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import java.util.Arrays;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class Post_toString_ceffa8036e_Test {

    private Post post;

    @BeforeEach
    public void setUp() {
        post = new Post();
        post.setProfile("Java Developer");
        post.setDesc("Backend Developer");
        post.setExp(3);
        post.setTechs(new String[]{"Java", "Spring Boot", "Microservices"});
    }

    @Test
    public void testToString() {
        String expected = "Post{" +
                "profile='Java Developer'" +
                ", desc='Backend Developer'" +
                ", exp=3" +
                ", techs=" + Arrays.toString(new String[]{"Java", "Spring Boot", "Microservices"}) +
                '}';
        assertEquals(expected, post.toString());
    }

    @Test
    public void testToStringWithNoTechs() {
        post.setTechs(null);
        String expected = "Post{" +
                "profile='Java Developer'" +
                ", desc='Backend Developer'" +
                ", exp=3" +
                ", techs=null" +
                '}';
        assertEquals(expected, post.toString());
    }
}
