// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
public class Post_setTechs_1b061b0fa7_Test {

    private Post post;

    @BeforeEach
    public void setUp() {
        post = new Post();
    }

    @Test
    public void testSetTechs_ValidInput() {
        String[] techs = {"Java", "Python", "C++"};
        post.setTechs(techs);
        assertArrayEquals(techs, post.getTechs());
    }

    @Test
    public void testSetTechs_NullInput() {
        post.setTechs(null);
        assertNull(post.getTechs());
    }
}
