// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class Post_toString_ceffa8036e_Test {

    @Test
    public void testToString() {
        Post post = new Post();
        post.setProfile("Software Developer");
        post.setDesc("Java Developer");
        post.setExp(5);
        String[] techs = {"Java", "Spring"};
        post.setTechs(techs);
        
        String expected = "Post{profile='Software Developer', desc='Java Developer', exp=5, techs=[Java, Spring]}";
        String actual = post.toString();
        
        Assertions.assertEquals(expected, actual);
    }

    @Test
    public void testToStringWithNullValues() {
        Post post = new Post();
        
        String expected = "Post{profile='null', desc='null', exp=0, techs=null}";
        String actual = post.toString();
        
        Assertions.assertEquals(expected, actual);
    }
}
