// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.springframework.data.mongodb.core.mapping.Document;
import java.util.Arrays;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

@Document
public class Post_setExp_4638d82240_Test {
    
    @Test
    public void testSetExp_Positive() {
        Job job = new Job();
        job.setExp(5);
        assertEquals(5, job.getExp());
    }
    
    @Test
    public void testSetExp_Zero() {
        Job job = new Job();
        job.setExp(0);
        assertEquals(0, job.getExp());
    }
    
    @Test
    public void testSetExp_Negative() {
        Job job = new Job();
        job.setExp(-5);
        assertEquals(-5, job.getExp());
    }
}
