// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class Post_getDesc_66e632b9da_Test {

    private Post post;

    @BeforeEach
    public void setup() {
        post = new Post();
    }

    @Test
    public void testGetDesc_WhenDescIsNotEmpty() {
        String expectedDesc = "This is a description";
        post.setDesc(expectedDesc);
        String actualDesc = post.getDesc();
        Assertions.assertEquals(expectedDesc, actualDesc);
    }

    @Test
    public void testGetDesc_WhenDescIsNull() {
        post.setDesc(null);
        String actualDesc = post.getDesc();
        Assertions.assertNull(actualDesc);
    }
}
