// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

@SpringBootTest
public class Post_setProfile_50f29a11fe_Test {

    @Autowired
    private Post post;

    @MockBean
    private SomeExternalService someExternalService;

    @Test
    public void testSetProfileSuccess() {
        String profile = "Software Developer";
        post.setProfile(profile);
        Assertions.assertEquals(profile, post.getProfile(), "The profile should be set correctly");
    }

    @Test
    public void testSetProfileNull() {
        String profile = null;
        post.setProfile(profile);
        Assertions.assertNull(post.getProfile(), "The profile should be null");
    }
}
