// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import springfox.documentation.service.ApiInfo;
import static org.junit.jupiter.api.Assertions.assertNotNull;

@SpringBootTest
public class JoblistingApplication_apiInfo_0779216cdc_Test {

    @Test
    public void testApiInfo() {
        final ApiInfoBuilder builder = new ApiInfoBuilder();
        ApiInfo apiInfo = builder.build();

        // Test if the object is not null
        assertNotNull(apiInfo, "ApiInfo should not be null");
    }

    @Test
    public void testApiInfoWithDetails() {
        final ApiInfoBuilder builder = new ApiInfoBuilder();
        builder.title("Test API");
        builder.description("This is a test API");
        builder.version("1.0.0");
        ApiInfo apiInfo = builder.build();

        // Test if the object is not null
        assertNotNull(apiInfo, "ApiInfo should not be null");
        // Test if the title matches
        assertEquals("Test API", apiInfo.getTitle(), "Title should match");
        // Test if the description matches
        assertEquals("This is a test API", apiInfo.getDescription(), "Description should match");
        // Test if the version matches
        assertEquals("1.0.0", apiInfo.getVersion(), "Version should match");
    }
}
