// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import springfox.documentation.service.ApiInfo;
import static org.junit.Assert.*;

@RunWith(SpringRunner.class)
@SpringBootTest
public class JoblistingApplication_apiInfo_0779216cdc_Test {

    @Test
    public void testApiInfo() {
        JoblistingApplication app = new JoblistingApplication();
        ApiInfo result = app.apiInfo();
        assertNotNull(result);
        assertEquals(result.getDescription(), "");
        assertEquals(result.getTitle(), "");
        assertEquals(result.getVersion(), "");
    }

    @Test
    public void testApiInfoNotNull() {
        JoblistingApplication app = new JoblistingApplication();
        ApiInfo result = app.apiInfo();
        assertNotNull(result);
    }

}
