// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.beans.factory.annotation.Autowired;
import springfox.documentation.spring.web.plugins.Docket;

import static org.junit.jupiter.api.Assertions.*;

@ExtendWith(MockitoExtension.class)
public class JoblistingApplication_api_24e94226d8_Test {

  @InjectMocks
  private JoblistingApplication joblistingApplication;

  @Autowired
  private Docket docket;

  @Test
  public void testApi() {
    Docket actualDocket = joblistingApplication.api();
    assertNotNull(actualDocket);
    assertEquals(docket.getDocumentationType(), actualDocket.getDocumentationType());
    assertNotNull(actualDocket.getGroupName());
    assertNotNull(actualDocket.getApiInfo());
    assertFalse(actualDocket.isUseDefaultResponseMessages());
  }
}
