/*
Test generated by RoostGPT for test Java_test using AI Type Vertex AI and AI Model code-bison-32k

 **Test Scenario 1: Verify if the Docket bean is created successfully.**

**Test Steps:**

1. Create a Spring Boot application with the provided code snippet.
2. Run the application and check if the Docket bean is created successfully.
3. Verify that the Docket bean is of type `Docket` and has the correct configuration.

**Expected Result:**

The Docket bean should be created successfully and should have the correct configuration.

**Test Scenario 2: Verify if the Docket bean is able to generate Swagger documentation.**

**Test Steps:**

1. Create a Spring Boot application with the provided code snippet.
2. Run the application and access the Swagger documentation at `localhost:8080/swagger-ui.html`.
3. Verify that the Swagger documentation is generated successfully and contains the expected endpoints and descriptions.

**Expected Result:**

The Swagger documentation should be generated successfully and should contain the expected endpoints and descriptions.

**Test Scenario 3: Verify if the Docket bean is able to exclude specific endpoints from Swagger documentation.**

**Test Steps:**

1. Create a Spring Boot application with the provided code snippet.
2. Add an annotation `@ApiIgnore` to a specific controller or method to exclude it from Swagger documentation.
3. Run the application and access the Swagger documentation at `localhost:8080/swagger-ui.html`.
4. Verify that the excluded endpoint is not present in the Swagger documentation.

**Expected Result:**

The excluded endpoint should not be present in the Swagger documentation.
*/
import com.telusko.joblisting.JoblistingApplication;
import io.springfox.documentation.spring.web.plugins.Docket;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Bean;
import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.service.ApiInfo;

@SpringBootTest
class JoblistingApplication_api_24e94226d8_Test {

    @Test
    void api_Docket() {
        JoblistingApplication joblistingApplication = new JoblistingApplication();
        Docket actual = joblistingApplication.api();
        Assertions.assertEquals(Docket.class, actual.getClass());
        // TODO: Add more assertions to verify the configuration of the Docket bean
    }

    @Test
    void apiInfo_ApiInfo() {
        JoblistingApplication joblistingApplication = new JoblistingApplication();
        ApiInfo actual = joblistingApplication.apiInfo();
        Assertions.assertEquals(ApiInfo.class, actual.getClass());
        // TODO: Add more assertions to verify the configuration of the ApiInfo bean
    }

    @Test
    void main() {
        // TODO: Add assertions to verify the behavior of the main method
        JoblistingApplication.main(new String[] {});
    }
}
