// Test generated by RoostGPT for test JavaUnitTest using AI Type Open AI and AI Model gpt-4

package com.telusko.joblisting;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.spi.DocumentationType;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
public class JoblistingApplication_api_24e94226d8_Test {

    @InjectMocks
    private JoblistingApplication joblistingApplication;

    @Mock
    private Docket docket;

    @BeforeEach
    void setUp() {
        when(joblistingApplication.api()).thenReturn(docket);
    }

    @Test
    public void testApiMethod() {
        Docket result = joblistingApplication.api();
        assertNotNull(result);
    }

    @Test
    public void testApiMethodWithDocumentationType() {
        Docket result = joblistingApplication.api();
        assertEquals(DocumentationType.SWAGGER_2, result.getDocumentationType());
    }
}
